# Generated by Django 4.2.13 on 2024-05-19 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None),
        ),
    ]
