# Generated by Django 4.2.6 on 2024-01-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goalscorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField()),
                ('goal_team', models.CharField()),
                ('home_team', models.CharField()),
                ('match_date', models.DateField()),
                ('minute', models.IntegerField()),
                ('own_goal', models.BooleanField()),
                ('penalty', models.BooleanField()),
                ('scorer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_score', models.IntegerField()),
                ('away_team', models.CharField()),
                ('city', models.CharField()),
                ('country', models.CharField()),
                ('home_score', models.IntegerField()),
                ('home_team', models.CharField()),
                ('match_date', models.DateField()),
                ('neutral', models.BooleanField()),
                ('tournament', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Shootouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField()),
                ('first_shooter', models.CharField()),
                ('home_team', models.CharField()),
                ('match_date', models.DateField()),
                ('winner', models.CharField()),
            ],
        ),
    ]
